# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/hlocal/DAS/projects/lab_8/lab_8.srcs/sources_1/ip/vgaTextInterface_RAM/vgaTextInterface_RAM.xci
# IP: The module: 'vgaTextInterface_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/DAS/projects/lab_8/lab_8.gen/sources_1/ip/vgaTextInterface_RAM/vgaTextInterface_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaTextInterface_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/hlocal/DAS/projects/lab_8/lab_8.srcs/sources_1/ip/vgaTextInterface_RAM/vgaTextInterface_RAM.xci
# IP: The module: 'vgaTextInterface_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/DAS/projects/lab_8/lab_8.gen/sources_1/ip/vgaTextInterface_RAM/vgaTextInterface_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaTextInterface_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
