# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/hlocal/DAS/projects/project_final/project_final.srcs/sources_1/ip/fill_level_ram_1/fill_level_ram.xci
# IP: The module: 'fill_level_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/DAS/projects/project_final/project_final.gen/sources_1/ip/fill_level_ram_1/fill_level_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fill_level_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/hlocal/DAS/projects/project_final/project_final.srcs/sources_1/ip/fill_level_ram_1/fill_level_ram.xci
# IP: The module: 'fill_level_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/hlocal/DAS/projects/project_final/project_final.gen/sources_1/ip/fill_level_ram_1/fill_level_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fill_level_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
